[options]
; Database instellingen (Railway/Postgres)
db_host = db.bkavzcfnxjoaojlrluxx.supabase.co
db_port = 5432
db_user = postgres
db_password = @nHjMz65ED%kXF
db_name = postgres

; Addons path (je kan meerdere paden comma-separated zetten)
addons_path = addons

; Webserver instellingen
http_port = ${PORT}        ; Railway zet automatisch de poort via ${PORT}
proxy_mode = True          ; Zorgt dat Odoo de juiste headers pakt achter een proxy

; Optioneel maar aanbevolen
workers = 2                ; aantal workers voor productie
max_cron_threads = 1       ; cron jobs
logfile = /tmp/odoo.log    ; log file pad
