[options]

; Database instellingen (Railway/Postgres)
db_host = db.bkavzcfnxjoaojlrluxx.supabase.co
db_port = 5432
db_user = postgres
db_password = @nHjMz65ED%kXF
db_name = postgres

; Addons path
addons_path = addons

; Webserver instellingen
http_port = 8069        ; Odoo luistert standaard op 8069, Railway zet de juiste PORT via env
proxy_mode = True        ; Zorgt dat Odoo de juiste headers pakt achter een proxy

; Productie instellingen
workers = 2              ; aantal workers
max_cron_threads = 1     ; aantal cron threads
logfile = /tmp/odoo.log  ; logbestand
